#' Creates dashboard for the given table or folder with data
#'
#'
#'
#' @param table trips_output tibble from readTripsTable()
#'
#' @param append specifies if the output folder should be erased before creating
#'
#' @param dump.output.to folder that saves and configures yaml for simwrapper dashboard and all plots using functions:
#' plotModalSplitBarChart(),plotModalSplitPieChart(),plotModalShift().
#'
#' @return generates folder with content for simwrapper out of trips table
#'
#' @export
prepareSimwrapperDashboardFromTable <- function(table, dump.output.to = matsimDumpOutputDirectory, append = TRUE) {

  if (append == FALSE) {
    if (file.exists(dump.output.to)) {
      unlink(dump.output.to, recursive = TRUE)
    }
  }
  plotModalSplitBarChart(table,dump.output.to = dump.output.to,only.files = TRUE)
  plotModalSplitPieChart(table,dump.output.to = dump.output.to,only.files = TRUE)
  plotAverageTravelWait(table,dump.output.to = dump.output.to,only.files = TRUE)
  plotTripsByDistance(table,dump.output.to = dump.output.to,only.files = TRUE)
  plotTripDistanceByMode(table,dump.output.to = dump.output.to,only.files = TRUE)
  plotTripCountByDepTime(table,dump.output.to = dump.output.to,only.files = TRUE)
  plotStartActCountByDepTime(table,dump.output.to = dump.output.to,only.files = TRUE)
  plotEndActCountByArrTime(table,dump.output.to = dump.output.to,only.files = TRUE)
  #Not sure if it is needed
  #plotModalShift(table, table,dump.output.to = dump.output.to)
}



#' Creates dashboard for the given table or folder with data
#'
#'
#'
#' @param folder specifies data source folder with tripsOutput
#'
#' @param append specifies if the output folder should be erased before creating
#'
#' @param dump.output.to folder that saves and configures yaml for simwrapper dashboard and all plots
#'
#' @return tibble of output_trips from folder. Generates content needed for Simwrapper
#'
#' @export
prepareSimwrapperDashboardFromFolder <- function(folder = "./", dump.output.to = matsimDumpOutputDirectory, append = TRUE) {
  options(digits = 18)
  table = readTripsTable(folder)
  path = attr(table,"table_name")
  prepareSimwrapperDashboardFromTable(table,dump.output.to,append)

  crs = getCrsFromConfig(folder)
  if(!is.na(crs)){
    generateXYHexagonYaml(attr(table,"table_name"), crs, dump.output.to=dump.output.to)
    generateTransitYaml(folder, crs, dump.output.to=dump.output.to)
    generateCarrierYaml(folder, crs, dump.output.to=dump.output.to)
  }

  return(table)
}

#' Creates/adds XY hexagon definition of output trips to a summary dashboard
#'
#' @param pathToOutputTrips specifies path to a data source of output_trips
#' @param crs specifies an coordinate reference system of output_trips
#' @param dump.output.to path to an folder with dashboard
#'
#' @return changed file
#'
#' @export
generateXYHexagonYaml<- function(pathToOutputTrips,crs,dump.output.to = matsimDumpOutputDirectory)
{
  yaml_list <- list(
    header = list(tab = "Summary", title = "Dashboard", description = "Plots from output directory"),
    layout = list("1" = list(
      title =  "XY Hexagon of trip origings/destinations ",
      description = "generated by generateXYHexagonYaml()",
      type = "hexagons",
      width = 1,
      props = list(height = 10,
                   width=2,
                   file = pathToOutputTrips,
                   projection = crs,
                   zoom  = 10,
                   radius = 100,
                   maxHeight=20,
                   aggregations = list("OD Summary" = list(list(title = "origins",x = "start_x",y = "start_y"),
                                                           list(title = "destinations",x = "end_x",y = "end_y")))
      )
    )
    )
  )
  if (file.exists(paste0(dump.output.to, dashboard_file))) {
    yaml_from_directory <- read_yaml(paste0(dump.output.to, dashboard_file))
    yaml_from_directory$layout <- append(yaml_from_directory$layout, list(new_row = list(
      title =  "XY Hexagon of trip origins/destinations ",
      description = "generated by generateXYHexagonYaml()",
      type = "hexagons",
      height = 10,
      width = 2,
      props = list(
                   file = pathToOutputTrips,
                   projection = crs,
                   zoom  = 10,
                   radius = 100,
                   maxHeight=20,
                   aggregations = list("OD Summary" = list(list(title = "origins",x = "start_x",y = "start_y"),
                                                           list(title = "destinations",x = "end_x",y = "end_y")))
      )
    )))
    names(yaml_from_directory$layout) <- 1:length(names(yaml_from_directory$layout))

    write_yaml(yaml_from_directory, paste0(dump.output.to, dashboard_file))
  } else {
    write_yaml(yaml_list, paste0(dump.output.to, dashboard_file))
  }
}

#' Creates/adds transit dashboard panel if output_transitSchedule.xml.gz exists
#'
#' @param folder folder containing output_transitSchedule.xml.gz
#' @param crs specifies an coordinate reference system of output_network
#' @param dump.output.to path to an folder with dashboard
#'
#' @return changed file
#'
#' @export
generateTransitYaml<- function(folder, crs, dump.output.to = matsimDumpOutputDirectory) {
  # check whether output_transitSchedule.xml.gz exists
  files <- list.files(folder, full.names = TRUE)
  exists <- grep("output_transitSchedule\\.xml\\.gz$", files)
  if (length(exists) == 0) return()

  # build YAML
  transit_yaml_file = 'dashboard-2-transit.yaml'
  yaml_list <- list(
    header = list(tab = "Transit"),
    layout = list("transit" = list(
      title =  "Transit network",
      type = "transit",
      height = 10,
      props = list(transitSchedule = "*output_transitSchedule.xml.gz",
                   network = "*output_network.xml.gz")
    )
    )
  )

  ofile = paste0(dump.output.to, '/', transit_yaml_file)
  print(paste('Writing:', ofile))
  write_yaml(yaml_list, ofile)
}

#' Creates/adds carriers dashboard panel if output_carriers.xml.gz exists
#'
#' @param folder folder containing output_carriers.xml.gz
#' @param crs specifies an coordinate reference system of output_network
#' @param dump.output.to path to an folder with dashboard
#'
#' @return changed file
#'
#' @export
generateCarrierYaml <- function(folder, crs, dump.output.to = matsimDumpOutputDirectory) {
  # check whether output_carriers.xml.gz exists
  files <- list.files(folder, full.names = TRUE)
  exists <- grep("output_carriers\\.xml\\.gz$", files, value=TRUE)
  if (length(exists) == 0) return()

  # build YAML
  yaml_file = 'dashboard-3-carriers.yaml'
  yaml_list <- list(
    header = list(tab = "Carriers"),
    layout = list("carriers" = list(
      title =  "Carriers",
      type = "carriers",
      height = 10,
      props = list(carriers = "*output_carriers.xml.gz",
                   network = "*output_network.xml.gz")
    ))
  )

  ofile = paste0(dump.output.to, '/', yaml_file)
  print(paste('Writing:', ofile))
  write_yaml(yaml_list, ofile)
}


clearDashboard<- function(matsimOutputFolder){
  if (file.exists(dump.output.to)) {
    unlink(dump.output.to, recursive = TRUE)
  }
}
